export const sections = [
  {
    id: 1,
    title: "1. Luxury Sheets Are Being Hit With Tariffs. Ours Aren’t.",
    description:
      "Many premium beddings brands source their materials from overseas—then pass import tariffs directly onto you. Our premium Sheets are designed to deliver luxury, cooling, and cleanliness without the markup. You get the same high-end quality (or better), without the government taking a cut.",
    mobileDescription:
      "Many premium beddings brands source their materials from overseas—then pass import tariffs directly onto you. Miracle Made® Sheets are designed to deliver luxury, cooling, and cleanliness without the markup. You get the same high-end quality (or better), without the government taking a cut.",
    image: require("../assets/man-vs-section-1.webp"),
    alt: "Tariff price hike sticker on a folded sheet",
    type: "light",
    position: "left",
    content: {
      paddingMinLeft: 34,
      paddingMaxLeft: 112,
      paddingMinRight: 14,
      paddingMaxRight: 112,
      paddingMinTop: 40,
      paddingMaxTop: 184,
      paddingMinBottom: 33,
      paddingMaxBottom: 187,
    },
    paragraph: {
      w414: 345,
      w948: 808.44,
      w949: 334.77,
      w1440: 497,
    },
  },
  {
    id: 2,
    title: "2. Space-Age Innovation Without Space-Age Prices",
    description:
      "Our temperature-regulating sheets were inspired by the same materials NASA uses to keep astronauts cool. And thanks to our unique approach to sourcing and manufacturing, you won’t see those savings eaten up by hidden costs or extra duties. Just smarter comfort, built for Earth.",
    mobileDescription:
      "Our temperature-regulating sheets were inspired by the same materials NASA uses to keep astronauts cool. And thanks to our unique approach to sourcing and manufacturing, you won’t see those savings eaten up by hidden costs or extra duties. Just smarter comfort, built for Earth.",
    image: require("../assets/man-vs-section-2.webp"),
    alt: "Woman sleeping peacefully under sheets with curvy lines showing the cooling effect of the sheets",
    type: "dark",
    position: "right",
    content: {
      paddingMinLeft: 34,
      paddingMaxLeft: 105,
      paddingMinRight: 35,
      paddingMaxRight: 105,
      paddingMinTop: 40,
      paddingMaxTop: 199,
      paddingMinBottom: 53,
      paddingMaxBottom: 198,
    },
    paragraph: {
      w414: 345,
      w948: 805.66,
      w949: 332.02,
      w1440: 511,
    },
  },
  {
    id: 3,
    title: "3. Fewer Washes = Lower Water Bills = Big Wins",
    description:
      "Our silver-infused fibers fight bacteria and odors naturally. That means you can wash less, save more, and feel fresher every night. Traditional sheets just can’t compete—and every unnecessary wash is money down the drain.",
    mobileDescription:
      "Our silver-infused fibers fight bacteria and odors naturally. That means you can wash less, save more, and feel fresher every night.  Traditional sheets just can’t compete—and every unnecessary wash is money down the drain.",
    image: require("../assets/man-vs-section-3.webp"),
    alt: "Man adding sheets into a washing machine",
    type: "light",
    position: "left",
    content: {
      paddingMinLeft: 34,
      paddingMaxLeft: 111,
      paddingMinRight: 35,
      paddingMaxRight: 113,
      paddingMinTop: 40,
      paddingMaxTop: 199,
      paddingMinBottom: 37,
      paddingMaxBottom: 198,
    },
    paragraph: {
      w414: 345,
      w948: 798.41,
      w949: 324.75,
      w1440: 497,
    },
  },
  {
    id: 4,
    title: "4. Why Pay 2-3x More For Sheets That Do Less?",
    description:
      "Most “luxury” brands aren’t antibacterial. They don’t regulate temperature. And they certainly don’t offer real savings. Our premium Sheets deliver softness, cleanliness, and cooling in one high-tech package—without tariff bloat.",
    mobileDescription:
      "Most “luxury” brands aren’t antibacterial. They don’t regulate temperature. And they certainly don’t offer real savings. Miracle Made® Sheets deliver softness, cleanliness, and cooling in one high-tech package—without tariff bloat.",
    image: require("../assets/man-vs-section-4.webp"),
    alt: "A woman's hands adding final touches to making a bed",
    type: "dark",
    position: "right",
    content: {
      paddingMinLeft: 34,
      paddingMaxLeft: 110,
      paddingMinRight: 38,
      paddingMaxRight: 97,
      paddingMinTop: 27,
      paddingMaxTop: 201,
      paddingMinBottom: 53,
      paddingMaxBottom: 202,
    },
    paragraph: {
      w414: 345,
      w948: 805.73,
      w949: 332.1,
      w1440: 511,
    },
  },
  {
    id: 5,
    title: "5. The Hidden Cost of Dirty Sheets? Your Skin.",
    description:
      "Regular sheets trap bacteria that irritate skin and clog pores. Our silver-infused our premium Sheets help reduce up to 99.7% of bacteria growth, making them a game-changer for anyone who wants clearer skin and fewer breakouts.",
    mobileDescription:
      "Regular sheets trap bacteria that irritate skin and clog pores. Our silver-infused Miracle Made® Sheets help reduce up to 99.7% of bacteria growth, making them a game-changer for anyone who wants clearer skin and fewer breakouts.",
    image: require("../assets/man-vs-section-5.webp"),
    alt: "A man with a happy smile cosied up under sheets with his arm under the pillow",
    type: "light",
    position: "left",
    content: {
      paddingMinLeft: 34,
      paddingMaxLeft: 120,
      paddingMinRight: 35,
      paddingMaxRight: 121,
      paddingMinTop: 40,
      paddingMaxTop: 199,
      paddingMinBottom: 47,
      paddingMaxBottom: 198,
    },
    paragraph: {
      w414: 345,
      w948: 789.52,
      w949: 315.86,
      w1440: 480,
    },
  },
  {
    id: 6,
    title: "6. Try Them. Love Them. Or Get Your Money Back.",
    description:
      "No fine print. No hassle. No tariffs. If you don’t love our premium fabric sheets after 30 nights of better sleep, we’ll refund every cent. We’re confident you’ll never look at regular sheets the same way again.",
    mobileDescription:
      "No fine print. No hassle. No tariffs. If you don’t love Miracle Made® Sheets after 30 nights of better sleep, we’ll refund every cent. We’re confident you’ll never look at regular sheets the same way again.",
    image: require("../assets/man-vs-section-6.webp"),
    alt: "A hand holding a mobile phone hinting at a risk free trial, free USA shipping and free returns",
    mobileAlt: "Happy older woman with a big smile on her face holding the miracle sheet product in her hands",
    type: "dark",
    position: "right",
    content: {
      paddingMinLeft: 34,
      paddingMaxLeft: 87,
      paddingMinRight: 33,
      paddingMaxRight: 84,
      paddingMinTop: 39,
      paddingMaxTop: 212,
      paddingMinBottom: 62,
      paddingMaxBottom: 211,
    },
    paragraph: {
      w414: 345,
      w948: 826.85,
      w949: 353.25,
      w1440: 511,
    },
  },
];
